# Alertmanager configuration for Suna/Renum backend
# This configuration defines how alerts are routed and delivered

global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@renum.com.br'
  smtp_auth_username: 'alerts@renum.com.br'
  smtp_auth_password: 'your_email_password'
  smtp_require_tls: true

# Route configuration
route:
  # Default receiver for all alerts
  receiver: 'default-receiver'
  
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service']
  
  # Wait time before sending initial notification
  group_wait: 10s
  
  # Wait time before sending additional notifications for the same group
  group_interval: 10s
  
  # Wait time before sending repeat notifications
  repeat_interval: 1h

  # Sub-routes for specific alert types
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 30m
      
    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 2h

# Receivers define how to send notifications
receivers:
  # Default receiver - basic email notification
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@renum.com.br'
        subject: '[ALERT] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  # Critical alerts - multiple notification channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@renum.com.br,dev-team@renum.com.br'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} - IMMEDIATE ACTION REQUIRED'
        body: |
          CRITICAL ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately!

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'dev-team@renum.com.br'
        subject: '[WARNING] {{ .GroupLabels.alertname }}'
        body: |
          WARNING ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt }}
          {{ end }}