# Grafana datasource configuration for Prometheus
# This file configures Prometheus as the primary data source for Grafana

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
    # Basic settings
    basicAuth: false
    withCredentials: false
    
    # JSON data for additional configuration
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      
      # Enable exemplars for tracing integration
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
      
      # Custom query parameters
      customQueryParameters: ''
      
      # Prometheus-specific settings
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      
      # Cache settings
      cacheLevel: High
      
      # Query editor settings
      disableMetricsLookup: false
      
    # Secure JSON data (for sensitive configuration)
    secureJsonData: {}
    
    # Version and other metadata
    version: 1
    uid: prometheus-uid
    
  # Optional: Add Alertmanager as a datasource for alert management
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    
    jsonData:
      implementation: prometheus
      
    version: 1
    uid: alertmanager-uid