@echo off
echo Atualizando referências de "Suna backend" para "backend"...

echo Atualizando docker-compose.yaml...
powershell -Command "(Get-Content docker-compose.yaml) -replace './Suna backend', './backend' -replace 'Suna backend', 'backend' | Set-Content docker-compose.yaml"

echo Atualizando start.py...
powershell -Command "(Get-Content start.py) -replace 'cd \"Suna backend\"', 'cd backend' -replace 'Suna backend', 'backend' | Set-Content start.py"

echo Atualizando .github/workflows/docker-build.yml...
powershell -Command "(Get-Content .github/workflows/docker-build.yml) -replace './Suna backend', './backend' -replace 'Suna backend', 'backend' | Set-Content .github/workflows/docker-build.yml"

echo Atualizando setup.py...
powershell -Command "(Get-Content setup.py) -replace 'Suna backend', 'backend' | Set-Content setup.py"

echo Atualizando DIRECTORY_RENAME_CHANGES.md...
powershell -Command "(Get-Content DIRECTORY_RENAME_CHANGES.md) -replace 'Suna backend', 'backend' | Set-Content DIRECTORY_RENAME_CHANGES.md"

echo Verificando se há outras referências...
powershell -Command "Get-ChildItem -Path . -Recurse -File -Include *.py,*.yml,*.yaml,*.md,*.sh,*.bat | Select-String -Pattern 'Suna backend' | Format-Table Path,LineNumber,Line -AutoSize"

echo Concluído!